REDIS:
  HOST: "localhost"
  PORT: "6379"
  PASSWORD: ""
  DB: 0

TOKEN:
  CHARSET: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  LENGTH: 11
  POOL_SIZE: 10

APP:
  PORT: 3333
  READ_TIMEOUT: 30
  WRITE_TIMEOUT: 90
  IDLE_TIMEOUT: 120
